const actiontype = {
   DATAKELAS: 'DATA_KELAS',
   SEMUAKELAS: 'SEMUA_KELAS',
   TUGASKELAS: 'TUGAS_KELAS',
   TUGASKELASKIRIM: 'TUGAS_KELAS_KIRIM',
   NILAITUGAS: 'NILAI_TUGAS',
   LISTNILAITUGAS: 'LIST_NILAI_TUGAS',
   DATAKOMEN: 'DATA_KOMEN',
   DATALIKE: 'DATA_LIKE',
}

export default actiontype;
